services:
  db:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: inventory_adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build:
      context: .                # root folder
      dockerfile: api/Dockerfile
    container_name: api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
    ports:
      - "8500:8500"
    depends_on:
      - db

  web_app:
    build:
      context: .                # root folder
      dockerfile: web_app/Dockerfile
    container_name: web_app
    environment:
      - API_URL=http://api:8500
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - api

